description: Stack to create Reinforcement learning agents and policies using Gym and Deep Learning
name: RL-gym
display-name: RL-gym
picture: stack.png
category: Backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility: # Put a list of technologies compatible with the stack
  - Python
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies 
  - Python 
about: docs/about.md
use-cases:
  - title: Use Case Title
    content: docs/use-case.md
    stackfile: stackfiles/default.yaml